### ISSUE TITLE
Implementar 'GitHub Action' para Testar e Validar Builds Automaticamente

### ISSUE THREAD

**Issue by thiag0bezerra** [convergencia-xyz/convergencia#2]
Erros podem passar desapercebidos e só serem detectados durante a tentaiva de deploy para produção.
Pensando nisso, é necessária a implementação  de uma [Github Action para testar automaticamente Pull Requests](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs)

```
19:09:27.264	[INFO] Docusaurus version: 3.4.0
19:09:27.264	Node version: v18.17.1
19:09:27.265	[ERROR] Error: Unable to build website for locale pt-br.
19:09:27.266	    at tryToBuildLocale (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
19:09:27.266	    at async /opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:65:9
19:09:27.266	    at async mapAsyncSequential (/opt/buildhome/repo/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
19:09:27.266	    at async Command.build (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
19:09:27.266	  [cause]: Error: Docusaurus found broken links!
```

**Comment by JonatasMSS** [comment]
Opa Thiago, criei um workflow pra o github action. Já executei o pull request para tu aceitar. Depois, é só testar e verificar o funcionamento.
Qualquer coisa, tu me fala se precisar de alguma alteração.

**Comment by thiag0bezerra** [comment]
Concluído
